# Type dvc-help in this file and hit enter to get more information on how the extension can help to setup pipelines
stages:
  data_prepare:
    cmd: poetry run python src/data/data_prepare.py
    deps:
    - src/data/data_prepare.py
    - data/prepared_data
    - data/initial_data
    outs:
    - data/prepared_data/prepared_data.csv
  training:
    cmd: poetry run python src/models/model_train.py
    deps:
    - src/models/model_train.py
    - data/initial_data/target.csv
    - data/prepared_data/prepared_data.csv
    outs:
    - models/linear_model.pickle
